"""Initial migration with seeding.

Revision ID: c29f11021c21
Revises: 
Create Date: 2024-06-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Text, Numeric

# revision identifiers, used by Alembic.
revision = 'c29f11021c21'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('student_id', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed the database with actual courses
    courses_table = table('course',
        column('id', sa.Integer),
        column('title', sa.String),
        column('description', sa.Text),
        column('amount', sa.Numeric)
    )

    sample_courses = [
        {
            'id': 1,
            'title': 'Introduction to Python Programming',
            'description': 'This course provides a comprehensive introduction to Python programming. Students will learn the basics of Python syntax, data structures, and libraries. By the end of the course, they will be able to write simple scripts and understand more complex programs. Topics include variables, loops, functions, and modules. Students will also work on practical projects to solidify their understanding and apply their skills in real-world scenarios.',
            'amount': 299.99
        },
        {
            'id': 2,
            'title': 'Data Science with R',
            'description': 'In this course, students will explore the powerful tools of R for data science. The course covers data manipulation, visualization, and statistical modeling. Students will learn to work with data frames, create compelling visualizations, and perform various statistical analyses. The curriculum includes hands-on projects where students will apply their knowledge to analyze real datasets and draw meaningful insights from them.',
            'amount': 499.99
        },
        {
            'id': 3,
            'title': 'Web Development with JavaScript',
            'description': 'This course is designed to teach students the fundamentals of web development using JavaScript. Students will learn how to create dynamic and interactive web pages. Topics include HTML, CSS, and JavaScript basics, as well as more advanced concepts like AJAX, APIs, and Node.js. By the end of the course, students will have built several web applications and will have a solid foundation in web development.',
            'amount': 399.99
        },
        {
            'id': 4,
            'title': 'Machine Learning with Python',
            'description': 'This course introduces students to the exciting field of machine learning using Python. Students will learn about various machine learning algorithms, including supervised and unsupervised learning. The course covers data preprocessing, model training, evaluation, and deployment. Students will work on practical projects involving real-world datasets to gain hands-on experience in building and deploying machine learning models.',
            'amount': 599.99
        },
        {
            'id': 5,
            'title': 'Digital Marketing Strategies',
            'description': 'This course provides an in-depth look at digital marketing strategies. Students will learn about search engine optimization (SEO), social media marketing, email marketing, and pay-per-click advertising. The course also covers content marketing and analytics. By the end of the course, students will be able to develop and implement comprehensive digital marketing plans to promote businesses and engage with customers effectively.',
            'amount': 349.99
        },
        {
            'id': 6,
            'title': 'Financial Analysis and Modeling',
            'description': 'In this course, students will learn the essential skills of financial analysis and modeling. The curriculum covers financial statements, ratio analysis, forecasting, and valuation techniques. Students will also learn to use Excel for building financial models. Practical case studies will help students apply their knowledge to analyze real companies and make informed financial decisions. This course is ideal for aspiring financial analysts and business professionals.',
            'amount': 449.99
        },
        {
            'id': 7,
            'title': 'Graphic Design with Adobe Illustrator',
            'description': 'This course teaches students how to use Adobe Illustrator for graphic design. Students will learn about vector graphics, typography, color theory, and design principles. The course includes hands-on projects where students will create logos, illustrations, and other graphic design elements. By the end of the course, students will have a portfolio of their work and a strong understanding of graphic design fundamentals.',
            'amount': 299.99
        },
        {
            'id': 8,
            'title': 'Cybersecurity Fundamentals',
            'description': 'This course provides a comprehensive overview of cybersecurity. Students will learn about network security, encryption, threat analysis, and risk management. The course also covers cybersecurity policies and best practices. Students will work on practical projects to identify and mitigate security vulnerabilities. By the end of the course, students will have a solid foundation in cybersecurity principles and practices.',
            'amount': 549.99
        },
        {
            'id': 9,
            'title': 'Project Management Professional (PMP) Exam Preparation',
            'description': 'This course prepares students for the Project Management Professional (PMP) exam. The curriculum covers the PMBOK Guide, including project integration, scope, time, cost, quality, human resources, communication, risk, procurement, and stakeholder management. Students will take practice exams and work on case studies to apply their knowledge. By the end of the course, students will be ready to pass the PMP exam and advance their careers in project management.',
            'amount': 599.99
        },
        {
            'id': 10,
            'title': 'Introduction to Artificial Intelligence',
            'description': 'This course introduces students to the fundamentals of artificial intelligence (AI). Students will learn about AI concepts, including machine learning, natural language processing, and robotics. The course covers AI techniques and algorithms, as well as their applications in various industries. Students will work on projects involving AI tools and technologies to gain practical experience. By the end of the course, students will have a solid understanding of AI and its potential impact on the future.',
            'amount': 699.99
        }
    ]

    op.bulk_insert(courses_table, sample_courses)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
